import type { Match, Team } from "./types"

const T = (code: string, name: string, flag: string): Team => ({ code, name, flag })

/** Alle 48 Teilnehmer der FIFA WM 2026, geordnet nach Vorrundengruppen A–L. */
export const TEAMS = {
  // Gruppe A
  MEX: T("MEX", "Mexiko", "🇲🇽"),
  RSA: T("RSA", "Südafrika", "🇿🇦"),
  KOR: T("KOR", "Südkorea", "🇰🇷"),
  CZE: T("CZE", "Tschechien", "🇨🇿"),
  // Gruppe B
  CAN: T("CAN", "Kanada", "🇨🇦"),
  BIH: T("BIH", "Bosnien-Herzegowina", "🇧🇦"),
  QAT: T("QAT", "Katar", "🇶🇦"),
  SUI: T("SUI", "Schweiz", "🇨🇭"),
  // Gruppe C
  BRA: T("BRA", "Brasilien", "🇧🇷"),
  MAR: T("MAR", "Marokko", "🇲🇦"),
  HAI: T("HAI", "Haiti", "🇭🇹"),
  SCO: T("SCO", "Schottland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
  // Gruppe D
  USA: T("USA", "USA", "🇺🇸"),
  PAR: T("PAR", "Paraguay", "🇵🇾"),
  AUS: T("AUS", "Australien", "🇦🇺"),
  TUR: T("TUR", "Türkei", "🇹🇷"),
  // Gruppe E
  GER: T("GER", "Deutschland", "🇩🇪"),
  CUW: T("CUW", "Curaçao", "🇨🇼"),
  CIV: T("CIV", "Elfenbeinküste", "🇨🇮"),
  ECU: T("ECU", "Ecuador", "🇪🇨"),
  // Gruppe F
  NED: T("NED", "Niederlande", "🇳🇱"),
  JPN: T("JPN", "Japan", "🇯🇵"),
  SWE: T("SWE", "Schweden", "🇸🇪"),
  TUN: T("TUN", "Tunesien", "🇹🇳"),
  // Gruppe G
  BEL: T("BEL", "Belgien", "🇧🇪"),
  EGY: T("EGY", "Ägypten", "🇪🇬"),
  IRN: T("IRN", "Iran", "🇮🇷"),
  NZL: T("NZL", "Neuseeland", "🇳🇿"),
  // Gruppe H
  ESP: T("ESP", "Spanien", "🇪🇸"),
  CPV: T("CPV", "Kap Verde", "🇨🇻"),
  KSA: T("KSA", "Saudi-Arabien", "🇸🇦"),
  URU: T("URU", "Uruguay", "🇺🇾"),
  // Gruppe I
  FRA: T("FRA", "Frankreich", "🇫🇷"),
  SEN: T("SEN", "Senegal", "🇸🇳"),
  IRQ: T("IRQ", "Irak", "🇮🇶"),
  NOR: T("NOR", "Norwegen", "🇳🇴"),
  // Gruppe J
  ARG: T("ARG", "Argentinien", "🇦🇷"),
  ALG: T("ALG", "Algerien", "🇩🇿"),
  AUT: T("AUT", "Österreich", "🇦🇹"),
  JOR: T("JOR", "Jordanien", "🇯🇴"),
  // Gruppe K
  POR: T("POR", "Portugal", "🇵🇹"),
  COD: T("COD", "DR Kongo", "🇨🇩"),
  UZB: T("UZB", "Usbekistan", "🇺🇿"),
  COL: T("COL", "Kolumbien", "🇨🇴"),
  // Gruppe L
  ENG: T("ENG", "England", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
  CRO: T("CRO", "Kroatien", "🇭🇷"),
  GHA: T("GHA", "Ghana", "🇬🇭"),
  PAN: T("PAN", "Panama", "🇵🇦"),
} as const

/** Platzhalter für K.o.-Paarungen, die erst im Turnierverlauf feststehen. */
const groupWinner = (group: string): Team => ({ code: `1${group}`, name: `Sieger Gruppe ${group}`, flag: "❓" })
const groupRunnerUp = (group: string): Team => ({ code: `2${group}`, name: `Zweiter Gruppe ${group}`, flag: "❓" })
const groupThird = (groups: string): Team => ({
  code: `3${groups}`,
  name: `Dritter aus ${groups.split("").join("/")}`,
  flag: "❓",
})
const winnerOf = (matchId: number): Team => ({ code: `W${matchId}`, name: `Sieger Spiel ${matchId}`, flag: "❓" })
const loserOf = (matchId: number): Team => ({ code: `V${matchId}`, name: `Verlierer Spiel ${matchId}`, flag: "❓" })

/**
 * Offizieller Spielplan der FIFA WM 2026: 104 Spiele, 11. Juni – 19. Juli 2026.
 * Quelle: FIFA Match Schedule (Stand 10. April 2026), Anstosszeiten in UTC.
 * Resultate werden nachgetragen, sobald Spiele beendet sind.
 */
export const MATCHES: Match[] = [
  // Gruppenphase
  {
    id: 1,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-11T19:00:00Z",
    venue: "Mexiko-Stadt",
    home: TEAMS.MEX,
    away: TEAMS.RSA,
  },
  {
    id: 2,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-12T02:00:00Z",
    venue: "Guadalajara",
    home: TEAMS.KOR,
    away: TEAMS.CZE,
  },
  {
    id: 3,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-12T19:00:00Z",
    venue: "Toronto",
    home: TEAMS.CAN,
    away: TEAMS.BIH,
  },
  {
    id: 4,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-13T01:00:00Z",
    venue: "Los Angeles",
    home: TEAMS.USA,
    away: TEAMS.PAR,
  },
  {
    id: 5,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-14T01:00:00Z",
    venue: "Boston",
    home: TEAMS.HAI,
    away: TEAMS.SCO,
  },
  {
    id: 6,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-13T04:00:00Z",
    venue: "Vancouver",
    home: TEAMS.AUS,
    away: TEAMS.TUR,
  },
  {
    id: 7,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-13T22:00:00Z",
    venue: "New York New Jersey",
    home: TEAMS.BRA,
    away: TEAMS.MAR,
  },
  {
    id: 8,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-13T19:00:00Z",
    venue: "San Francisco Bay Area",
    home: TEAMS.QAT,
    away: TEAMS.SUI,
  },
  {
    id: 9,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-14T23:00:00Z",
    venue: "Philadelphia",
    home: TEAMS.CIV,
    away: TEAMS.ECU,
  },
  {
    id: 10,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-14T17:00:00Z",
    venue: "Houston",
    home: TEAMS.GER,
    away: TEAMS.CUW,
  },
  {
    id: 11,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-14T20:00:00Z",
    venue: "Dallas",
    home: TEAMS.NED,
    away: TEAMS.JPN,
  },
  {
    id: 12,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-15T02:00:00Z",
    venue: "Monterrey",
    home: TEAMS.SWE,
    away: TEAMS.TUN,
  },
  {
    id: 13,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-15T22:00:00Z",
    venue: "Miami",
    home: TEAMS.KSA,
    away: TEAMS.URU,
  },
  {
    id: 14,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-15T16:00:00Z",
    venue: "Atlanta",
    home: TEAMS.ESP,
    away: TEAMS.CPV,
  },
  {
    id: 15,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-16T01:00:00Z",
    venue: "Los Angeles",
    home: TEAMS.IRN,
    away: TEAMS.NZL,
  },
  {
    id: 16,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-15T19:00:00Z",
    venue: "Seattle",
    home: TEAMS.BEL,
    away: TEAMS.EGY,
  },
  {
    id: 17,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-16T19:00:00Z",
    venue: "New York New Jersey",
    home: TEAMS.FRA,
    away: TEAMS.SEN,
  },
  {
    id: 18,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-16T22:00:00Z",
    venue: "Boston",
    home: TEAMS.IRQ,
    away: TEAMS.NOR,
  },
  {
    id: 19,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-17T01:00:00Z",
    venue: "Kansas City",
    home: TEAMS.ARG,
    away: TEAMS.ALG,
  },
  {
    id: 20,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-16T04:00:00Z",
    venue: "San Francisco Bay Area",
    home: TEAMS.AUT,
    away: TEAMS.JOR,
  },
  {
    id: 21,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-17T23:00:00Z",
    venue: "Toronto",
    home: TEAMS.GHA,
    away: TEAMS.PAN,
  },
  {
    id: 22,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-17T20:00:00Z",
    venue: "Dallas",
    home: TEAMS.ENG,
    away: TEAMS.CRO,
  },
  {
    id: 23,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-17T17:00:00Z",
    venue: "Houston",
    home: TEAMS.POR,
    away: TEAMS.COD,
  },
  {
    id: 24,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-18T02:00:00Z",
    venue: "Mexiko-Stadt",
    home: TEAMS.UZB,
    away: TEAMS.COL,
  },
  {
    id: 25,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-18T16:00:00Z",
    venue: "Atlanta",
    home: TEAMS.CZE,
    away: TEAMS.RSA,
  },
  {
    id: 26,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-18T19:00:00Z",
    venue: "Los Angeles",
    home: TEAMS.SUI,
    away: TEAMS.BIH,
  },
  {
    id: 27,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-18T22:00:00Z",
    venue: "Vancouver",
    home: TEAMS.CAN,
    away: TEAMS.QAT,
  },
  {
    id: 28,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-19T01:00:00Z",
    venue: "Guadalajara",
    home: TEAMS.MEX,
    away: TEAMS.KOR,
  },
  {
    id: 29,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-20T00:30:00Z",
    venue: "Philadelphia",
    home: TEAMS.BRA,
    away: TEAMS.HAI,
  },
  {
    id: 30,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-19T22:00:00Z",
    venue: "Boston",
    home: TEAMS.SCO,
    away: TEAMS.MAR,
  },
  {
    id: 31,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-20T03:00:00Z",
    venue: "San Francisco Bay Area",
    home: TEAMS.TUR,
    away: TEAMS.PAR,
  },
  {
    id: 32,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-19T19:00:00Z",
    venue: "Seattle",
    home: TEAMS.USA,
    away: TEAMS.AUS,
  },
  {
    id: 33,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-20T20:00:00Z",
    venue: "Toronto",
    home: TEAMS.GER,
    away: TEAMS.CIV,
  },
  {
    id: 34,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-21T00:00:00Z",
    venue: "Kansas City",
    home: TEAMS.ECU,
    away: TEAMS.CUW,
  },
  {
    id: 35,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-20T17:00:00Z",
    venue: "Houston",
    home: TEAMS.NED,
    away: TEAMS.SWE,
  },
  {
    id: 36,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-20T04:00:00Z",
    venue: "Monterrey",
    home: TEAMS.TUN,
    away: TEAMS.JPN,
  },
  {
    id: 37,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-21T22:00:00Z",
    venue: "Miami",
    home: TEAMS.URU,
    away: TEAMS.CPV,
  },
  {
    id: 38,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-21T16:00:00Z",
    venue: "Atlanta",
    home: TEAMS.ESP,
    away: TEAMS.KSA,
  },
  {
    id: 39,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-21T19:00:00Z",
    venue: "Los Angeles",
    home: TEAMS.BEL,
    away: TEAMS.IRN,
  },
  {
    id: 40,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-22T01:00:00Z",
    venue: "Vancouver",
    home: TEAMS.NZL,
    away: TEAMS.EGY,
  },
  {
    id: 41,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-23T00:00:00Z",
    venue: "New York New Jersey",
    home: TEAMS.NOR,
    away: TEAMS.SEN,
  },
  {
    id: 42,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-22T21:00:00Z",
    venue: "Philadelphia",
    home: TEAMS.FRA,
    away: TEAMS.IRQ,
  },
  {
    id: 43,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-22T17:00:00Z",
    venue: "Dallas",
    home: TEAMS.ARG,
    away: TEAMS.AUT,
  },
  {
    id: 44,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-23T03:00:00Z",
    venue: "San Francisco Bay Area",
    home: TEAMS.JOR,
    away: TEAMS.ALG,
  },
  {
    id: 45,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-23T20:00:00Z",
    venue: "Boston",
    home: TEAMS.ENG,
    away: TEAMS.GHA,
  },
  {
    id: 46,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-23T23:00:00Z",
    venue: "Toronto",
    home: TEAMS.PAN,
    away: TEAMS.CRO,
  },
  {
    id: 47,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-23T17:00:00Z",
    venue: "Houston",
    home: TEAMS.POR,
    away: TEAMS.UZB,
  },
  {
    id: 48,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-24T02:00:00Z",
    venue: "Guadalajara",
    home: TEAMS.COL,
    away: TEAMS.COD,
  },
  {
    id: 49,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-24T22:00:00Z",
    venue: "Miami",
    home: TEAMS.SCO,
    away: TEAMS.BRA,
  },
  {
    id: 50,
    stage: "Gruppenphase",
    group: "C",
    kickoff: "2026-06-24T22:00:00Z",
    venue: "Atlanta",
    home: TEAMS.MAR,
    away: TEAMS.HAI,
  },
  {
    id: 51,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-24T19:00:00Z",
    venue: "Vancouver",
    home: TEAMS.SUI,
    away: TEAMS.CAN,
  },
  {
    id: 52,
    stage: "Gruppenphase",
    group: "B",
    kickoff: "2026-06-24T19:00:00Z",
    venue: "Seattle",
    home: TEAMS.BIH,
    away: TEAMS.QAT,
  },
  {
    id: 53,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-25T01:00:00Z",
    venue: "Mexiko-Stadt",
    home: TEAMS.CZE,
    away: TEAMS.MEX,
  },
  {
    id: 54,
    stage: "Gruppenphase",
    group: "A",
    kickoff: "2026-06-25T01:00:00Z",
    venue: "Monterrey",
    home: TEAMS.RSA,
    away: TEAMS.KOR,
  },
  {
    id: 55,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-25T20:00:00Z",
    venue: "Philadelphia",
    home: TEAMS.CUW,
    away: TEAMS.CIV,
  },
  {
    id: 56,
    stage: "Gruppenphase",
    group: "E",
    kickoff: "2026-06-25T20:00:00Z",
    venue: "New York New Jersey",
    home: TEAMS.ECU,
    away: TEAMS.GER,
  },
  {
    id: 57,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-25T23:00:00Z",
    venue: "Dallas",
    home: TEAMS.JPN,
    away: TEAMS.SWE,
  },
  {
    id: 58,
    stage: "Gruppenphase",
    group: "F",
    kickoff: "2026-06-25T23:00:00Z",
    venue: "Kansas City",
    home: TEAMS.TUN,
    away: TEAMS.NED,
  },
  {
    id: 59,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-26T02:00:00Z",
    venue: "Los Angeles",
    home: TEAMS.TUR,
    away: TEAMS.USA,
  },
  {
    id: 60,
    stage: "Gruppenphase",
    group: "D",
    kickoff: "2026-06-26T02:00:00Z",
    venue: "San Francisco Bay Area",
    home: TEAMS.PAR,
    away: TEAMS.AUS,
  },
  {
    id: 61,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-26T19:00:00Z",
    venue: "Boston",
    home: TEAMS.NOR,
    away: TEAMS.FRA,
  },
  {
    id: 62,
    stage: "Gruppenphase",
    group: "I",
    kickoff: "2026-06-26T19:00:00Z",
    venue: "Toronto",
    home: TEAMS.SEN,
    away: TEAMS.IRQ,
  },
  {
    id: 63,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-27T03:00:00Z",
    venue: "Seattle",
    home: TEAMS.EGY,
    away: TEAMS.IRN,
  },
  {
    id: 64,
    stage: "Gruppenphase",
    group: "G",
    kickoff: "2026-06-27T03:00:00Z",
    venue: "Vancouver",
    home: TEAMS.NZL,
    away: TEAMS.BEL,
  },
  {
    id: 65,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-27T00:00:00Z",
    venue: "Houston",
    home: TEAMS.CPV,
    away: TEAMS.KSA,
  },
  {
    id: 66,
    stage: "Gruppenphase",
    group: "H",
    kickoff: "2026-06-27T00:00:00Z",
    venue: "Guadalajara",
    home: TEAMS.URU,
    away: TEAMS.ESP,
  },
  {
    id: 67,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-27T21:00:00Z",
    venue: "New York New Jersey",
    home: TEAMS.PAN,
    away: TEAMS.ENG,
  },
  {
    id: 68,
    stage: "Gruppenphase",
    group: "L",
    kickoff: "2026-06-27T21:00:00Z",
    venue: "Philadelphia",
    home: TEAMS.CRO,
    away: TEAMS.GHA,
  },
  {
    id: 69,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-28T02:00:00Z",
    venue: "Kansas City",
    home: TEAMS.ALG,
    away: TEAMS.AUT,
  },
  {
    id: 70,
    stage: "Gruppenphase",
    group: "J",
    kickoff: "2026-06-28T02:00:00Z",
    venue: "Dallas",
    home: TEAMS.JOR,
    away: TEAMS.ARG,
  },
  {
    id: 71,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-27T23:30:00Z",
    venue: "Miami",
    home: TEAMS.COL,
    away: TEAMS.POR,
  },
  {
    id: 72,
    stage: "Gruppenphase",
    group: "K",
    kickoff: "2026-06-27T23:30:00Z",
    venue: "Atlanta",
    home: TEAMS.COD,
    away: TEAMS.UZB,
  },
  // Sechzehntelfinale
  {
    id: 73,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-28T19:00:00Z",
    venue: "Los Angeles",
    home: groupRunnerUp("A"),
    away: groupRunnerUp("B"),
  },
  {
    id: 74,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-29T20:30:00Z",
    venue: "Boston",
    home: groupWinner("E"),
    away: groupThird("ABCDF"),
  },
  {
    id: 75,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-30T01:00:00Z",
    venue: "Monterrey",
    home: groupWinner("F"),
    away: groupRunnerUp("C"),
  },
  {
    id: 76,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-29T17:00:00Z",
    venue: "Houston",
    home: groupWinner("C"),
    away: groupRunnerUp("F"),
  },
  {
    id: 77,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-30T21:00:00Z",
    venue: "New York New Jersey",
    home: groupWinner("I"),
    away: groupThird("CDFGH"),
  },
  {
    id: 78,
    stage: "Sechzehntelfinale",
    kickoff: "2026-06-30T17:00:00Z",
    venue: "Dallas",
    home: groupRunnerUp("E"),
    away: groupRunnerUp("I"),
  },
  {
    id: 79,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-01T01:00:00Z",
    venue: "Mexiko-Stadt",
    home: groupWinner("A"),
    away: groupThird("CEFHI"),
  },
  {
    id: 80,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-01T16:00:00Z",
    venue: "Atlanta",
    home: groupWinner("L"),
    away: groupThird("EHIJK"),
  },
  {
    id: 81,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-02T00:00:00Z",
    venue: "San Francisco Bay Area",
    home: groupWinner("D"),
    away: groupThird("BEFIJ"),
  },
  {
    id: 82,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-01T20:00:00Z",
    venue: "Seattle",
    home: groupWinner("G"),
    away: groupThird("AEHIJ"),
  },
  {
    id: 83,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-02T23:00:00Z",
    venue: "Toronto",
    home: groupRunnerUp("K"),
    away: groupRunnerUp("L"),
  },
  {
    id: 84,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-02T19:00:00Z",
    venue: "Los Angeles",
    home: groupWinner("H"),
    away: groupRunnerUp("J"),
  },
  {
    id: 85,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-03T03:00:00Z",
    venue: "Vancouver",
    home: groupWinner("B"),
    away: groupThird("EFGIJ"),
  },
  {
    id: 86,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-03T22:00:00Z",
    venue: "Miami",
    home: groupWinner("J"),
    away: groupRunnerUp("H"),
  },
  {
    id: 87,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-04T01:30:00Z",
    venue: "Kansas City",
    home: groupWinner("K"),
    away: groupThird("DEIJL"),
  },
  {
    id: 88,
    stage: "Sechzehntelfinale",
    kickoff: "2026-07-03T18:00:00Z",
    venue: "Dallas",
    home: groupRunnerUp("D"),
    away: groupRunnerUp("G"),
  },
  // Achtelfinale
  {
    id: 89,
    stage: "Achtelfinale",
    kickoff: "2026-07-04T21:00:00Z",
    venue: "Philadelphia",
    home: winnerOf(74),
    away: winnerOf(77),
  },
  {
    id: 90,
    stage: "Achtelfinale",
    kickoff: "2026-07-04T17:00:00Z",
    venue: "Houston",
    home: winnerOf(73),
    away: winnerOf(75),
  },
  {
    id: 91,
    stage: "Achtelfinale",
    kickoff: "2026-07-05T20:00:00Z",
    venue: "New York New Jersey",
    home: winnerOf(76),
    away: winnerOf(78),
  },
  {
    id: 92,
    stage: "Achtelfinale",
    kickoff: "2026-07-06T00:00:00Z",
    venue: "Mexiko-Stadt",
    home: winnerOf(79),
    away: winnerOf(80),
  },
  {
    id: 93,
    stage: "Achtelfinale",
    kickoff: "2026-07-06T19:00:00Z",
    venue: "Dallas",
    home: winnerOf(83),
    away: winnerOf(84),
  },
  {
    id: 94,
    stage: "Achtelfinale",
    kickoff: "2026-07-07T00:00:00Z",
    venue: "Seattle",
    home: winnerOf(81),
    away: winnerOf(82),
  },
  {
    id: 95,
    stage: "Achtelfinale",
    kickoff: "2026-07-07T16:00:00Z",
    venue: "Atlanta",
    home: winnerOf(86),
    away: winnerOf(88),
  },
  {
    id: 96,
    stage: "Achtelfinale",
    kickoff: "2026-07-07T20:00:00Z",
    venue: "Vancouver",
    home: winnerOf(85),
    away: winnerOf(87),
  },
  // Viertelfinale
  {
    id: 97,
    stage: "Viertelfinale",
    kickoff: "2026-07-09T20:00:00Z",
    venue: "Boston",
    home: winnerOf(89),
    away: winnerOf(90),
  },
  {
    id: 98,
    stage: "Viertelfinale",
    kickoff: "2026-07-10T19:00:00Z",
    venue: "Los Angeles",
    home: winnerOf(93),
    away: winnerOf(94),
  },
  {
    id: 99,
    stage: "Viertelfinale",
    kickoff: "2026-07-11T21:00:00Z",
    venue: "Miami",
    home: winnerOf(91),
    away: winnerOf(92),
  },
  {
    id: 100,
    stage: "Viertelfinale",
    kickoff: "2026-07-12T01:00:00Z",
    venue: "Kansas City",
    home: winnerOf(95),
    away: winnerOf(96),
  },
  // Halbfinale
  {
    id: 101,
    stage: "Halbfinale",
    kickoff: "2026-07-14T19:00:00Z",
    venue: "Dallas",
    home: winnerOf(97),
    away: winnerOf(98),
  },
  {
    id: 102,
    stage: "Halbfinale",
    kickoff: "2026-07-15T19:00:00Z",
    venue: "Atlanta",
    home: winnerOf(99),
    away: winnerOf(100),
  },
  // Spiel um Platz 3 (Sieger/Verlierer der Halbfinals)
  {
    id: 103,
    stage: "Spiel um Platz 3",
    kickoff: "2026-07-18T21:00:00Z",
    venue: "Miami",
    home: loserOf(101),
    away: loserOf(102),
  },
  // Final
  {
    id: 104,
    stage: "Final",
    kickoff: "2026-07-19T19:00:00Z",
    venue: "New York New Jersey",
    home: winnerOf(101),
    away: winnerOf(102),
  },
]
